const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token, tab='session', live={status:'absent'}, unityCraft=null, saved, work, revision, selection=0, search='', busy=false, dirty=false;
const notice = message => { $('#notice').textContent=message; };
const itemOpts = () => work.items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.id)}</option>`).join('');
const chooser = (value, options) => `<select data-field="${esc(value)}">${options}</select>`;
const field = (label, value, key, type='text', opts='') => `<label>${esc(label)}<input name="${esc(key)}" type="${type}" value="${esc(value)}" ${opts}></label>`;
const badge = `<span class="badge draft">DRAFT · NOT IN GAME</span>`;
async function api(path, payload) {
  const response=await fetch('/api/'+path,{method:payload===undefined?'GET':'POST', headers:payload===undefined?{}:{'Content-Type':'application/json','X-Ward-CSRF':token}, body:payload===undefined?undefined:JSON.stringify(payload)});
  const value=await response.json(); if(!response.ok) throw Error(value.errors?.join('; ') || value.error || value.ack?.error?.message || 'Request failed'); return value;
}
async function refreshLive(){try{live=await api('status');}catch(e){live={status:'error',reason:e.message};} $('#connection').textContent=({connected:'LIVE · UNITY',stale:'STALE · NO COMMANDS',absent:'NO DEV PLAYER',unavailable:'NO PLAYABLE SESSION',incompatible:'INCOMPATIBLE BRIDGE',error:'ERROR'})[live.status]||'UNKNOWN'; $('#connection').className=live.status; $('#sample').textContent=live.status==='connected'?`${live.state.build?.version||'Build unknown'} · sample ${live.ageSeconds.toFixed(1)}s old`:live.reason||''; if(tab==='session'&&!busy) render();}
async function refreshDraft(){const r=await api('draft');saved=r.data;work=structuredClone(saved);revision=r.revision;dirty=false;render();}
async function refreshUnityCraft(){try{unityCraft=(await api('unity-crafting')).data;}catch(e){unityCraft=null;notice('Unity Editor crafting export unavailable: '+e.message);}render();}
async function saveDraft(){try{const r=await api('draft',{revision,data:work});saved=r.data;revision=r.revision;dirty=false;notice('Draft saved. Nothing changed in Unity.');render();}catch(e){notice('Draft NOT saved: '+e.message);}}
function actions(){return `<div class="row"><button id="save" ${dirty?'':'disabled'}>Save draft only</button><button id="discard" ${dirty?'':'disabled'}>Discard changes</button><button id="export">Export JSON</button><label class="file">Import JSON<input id="import" type="file" accept="application/json,.json"></label></div>`;}
function wrap(title,content){$('#view').innerHTML=`<div class="heading"><h2>${esc(title)}</h2>${tab==='session'?'':badge}</div>${content}`; $('#save')?.addEventListener('click',saveDraft);$('#discard')?.addEventListener('click',()=>{work=structuredClone(saved);dirty=false;notice('Unsaved edits discarded.');render();});$('#export')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(work,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ward-item-lab-draft-v1.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});$('#import')?.addEventListener('change',async e=>{try{const file=e.target.files[0];if(file.size>512*1024)throw Error('File exceeds 512 KiB');let obj=JSON.parse(await file.text());if(!confirm('Validate and replace the saved local draft with this JSON? This does not change Unity.'))return;const r=await api('import',{revision,data:obj});saved=r.data;work=structuredClone(saved);revision=r.revision;dirty=false;notice('Validated draft imported and saved locally. Nothing changed in Unity.');render();}catch(err){notice('Import failed; draft unchanged: '+err.message);}});}
async function command(value,confirmation){if(!live.state||live.status!=='connected'){notice('No fresh development player; command not sent.');return;}if(confirmation&&!confirm(confirmation))return;busy=true;render();try{const response=await api('command',value);live=response.status;notice('Unity acknowledged '+value.action+'. Refreshing authoritative sample…');await refreshLive();}catch(e){notice('Command not confirmed/applied: '+e.message);await refreshLive();}finally{busy=false;render();}}
function sessionForm(){const root=$('#view'),active=document.activeElement;return {values:Object.fromEntries([...root.querySelectorAll('input[name],select[name]')].map(el=>[el.name,el.value])),focus:root.contains(active)?active.name:null,range:root.contains(active)&&active.type==='text'?[active.selectionStart,active.selectionEnd]:null};}
function restoreSessionForm(form){const root=$('#view');for(const [name,value] of Object.entries(form.values)){const el=[...root.querySelectorAll('input[name],select[name]')].find(el=>el.name===name);if(!el)continue;if(el.tagName==='SELECT'){if([...el.options].some(option=>option.value===value))el.value=value;else {el.add(new Option(`Unavailable · ${value}`,value,true,true));el.dataset.unavailable='true';}}else el.value=value;}if(form.focus){const el=[...root.querySelectorAll('input[name],select[name]')].find(el=>el.name===form.focus);if(el){el.focus();if(form.range)el.setSelectionRange(...form.range);}}if(root.querySelector('select[name="itemId"]')?.dataset.unavailable==='true')root.querySelectorAll('[data-command^="dev.item."]').forEach(button=>button.disabled=true);}
function session(){const form=sessionForm(),state=live.state,connected=live.status==='connected',disabled=connected&&!busy?'':'disabled';if(!state){wrap('Session',`<article><h3>${esc($('#connection').textContent)}</h3><p>${esc(live.reason||'Start the opted-in native development player to see real telemetry.')}</p><p>No demo telemetry is shown. Draft recipes and loot remain editable offline.</p></article>`);return;}
const s=state.session||{},c=state.combat||{},t=state.tutorial||{},clock=state.clock||{},craft=state.crafting||{};
wrap('Native session · Unity',`<div class="cards"><article><h3>World</h3><dl><dt>State</dt><dd>${esc(s.state)}</dd><dt>Objective</dt><dd>${esc(s.objective)}</dd><dt>Credits</dt><dd>${esc(s.credits)}</dd><dt>Clock</dt><dd>${clock.available?esc(Number(clock.hour).toFixed(2))+' h':'Unavailable'}</dd></dl></article><article><h3>Player / tutorial</h3><dl><dt>Health</dt><dd>${c.available?esc(c.health)+' / '+esc(c.maxHealth):'Unavailable'}</dd><dt>Nano</dt><dd>${c.available?esc(c.nano):'Unavailable'}</dd><dt>Pistol</dt><dd>${c.available?(c.hasPistol?'Acquired':'Not acquired'):'Unavailable'}</dd><dt>Step</dt><dd>${t.available?esc(t.step):'Unavailable'}</dd><dt>Targets</dt><dd>${t.available?esc(t.targetsDown)+' / '+esc(t.targetsTotal):'Unavailable'}</dd></dl></article></div>
<article><h3>Crafting & weapon · live Unity</h3>${craft.available?`<dl><dt>Known recipes</dt><dd>${esc(craft.knownRecipes?.join(', ')||'None')}</dd><dt>Fabricator</dt><dd>${craft.fabricatorOpen?'Open · '+esc(craft.stationId):'Closed'}</dd><dt>Grip slot</dt><dd>${esc(craft.gripSlot||'Empty')}</dd><dt>Crafts / loot events</dt><dd>${esc(craft.crafts)} / ${esc(craft.lootEvents)}</dd><dt>Recoil</dt><dd>${esc(c.baseRecoil)} → ${esc(c.recoil)} points</dd><dt>Last shot kick</dt><dd>${esc(c.lastKickDegrees)}°</dd><dt>Crafting step</dt><dd>${esc(craft.tutorialStep)}</dd><dt>Last loot</dt><dd>${esc(craft.lastLoot||'None')}</dd></dl>`:esc(craft.reason||'Not initialized')}</article>
<article><h3>Authored clock</h3>${clock.available?`<div class="row">${field('Hour · 0 to <24',Number(clock.hour).toFixed(2),'hour','number','min="0" max="23.99" step="0.1"')}${field('Speed · 0.1 to 120',clock.speed,'speed','number','min="0.1" max="120" step="0.1"')}<button data-command="dev.time.set" ${disabled}>Set hour</button><button data-command="dev.time.speed" ${disabled}>Set speed</button><button data-command="dev.time.pause" ${disabled}>${clock.paused?'Resume':'Pause'}</button><button data-command="dev.time.reset" ${disabled}>Reset authored clock</button></div>`:esc(clock.reason||'Unavailable')}</article>
<article><h3>Weather</h3><p>Unavailable · ${esc(state.weather?.reason||'No weather system in this build')}. No surrogate control.</p></article>
<article><h3>Inventory & credits · Unity catalogue only</h3><table><thead><tr><th>Item ID</th><th>Name</th><th>Held</th></tr></thead><tbody>${(state.items||[]).map(i=>`<tr><td><code>${esc(i.id)}</code></td><td>${esc(i.name)}</td><td>${esc(i.quantity)}</td></tr>`).join('')}</tbody></table><div class="row"><label>Catalogue item<select name="itemId">${(state.items||[]).map(i=>`<option value="${esc(i.id)}">${esc(i.name)} · ${esc(i.id)}</option>`).join('')}</select></label>${field('Quantity · 1–99',1,'quantity','number','min="1" max="99" step="1"')}<button data-command="dev.item.grant" ${disabled}>Grant item</button><button data-command="dev.item.remove" ${disabled}>Remove item</button></div><div class="row">${field('Credits · 1–10000',1,'amount','number','min="1" max="10000" step="1"')}<button data-command="dev.credits.grant" ${disabled}>Grant credits</button><button data-command="dev.credits.remove" ${disabled}>Remove credits</button></div></article>
<article><h3>Authored encounters · no arbitrary spawn</h3>${(state.encounters||[]).map(e=>`<div class="entry"><div><strong>${esc(e.displayName)}</strong> <code>${esc(e.key)}</code><p>${e.spawned?'Spawned':'Not spawned'} · ${esc(e.remaining)} / ${esc(e.total)} remaining · ${e.cleared?'Cleared':'Active/awaiting'}</p></div><button data-encounter="activate" data-key="${esc(e.key)}" ${disabled||e.spawned?'disabled':''}>Activate</button><button data-encounter="reset" data-key="${esc(e.key)}" ${disabled||!e.spawned?'disabled':''}>Reset this encounter</button></div>`).join('')||'<p>Encounter data unavailable.</p>'}<button data-command="dev.range.raise" ${disabled}>Raise authored range targets</button></article>
<article><h3>Scoped interaction reset</h3><p>Clears city visit, spoken NPCs, shop visit flags, Lattice link and selected destination. Inventory, credits and tutorial remain unchanged.</p><button data-command="dev.interaction.resetCityVisit" ${disabled}>Reset city-visit/dialogue flags</button></article>`);
restoreSessionForm(form);$('#view').querySelector('select[name="itemId"]')?.addEventListener('change',e=>{delete e.target.dataset.unavailable;$('#view').querySelectorAll('[data-command^="dev.item."]').forEach(button=>button.disabled=!connected||busy);});$('#view').querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{const action=b.dataset.command, args={action};const input=n=>$('#view').querySelector(`[name="${n}"]`);if(action.startsWith('dev.item.')){if(input('itemId').dataset.unavailable==='true'){notice('Selected item is no longer in the live Unity catalogue; choose another item.');return;}args.itemId=input('itemId').value;args.quantity=Number(input('quantity').value);}if(action.startsWith('dev.credits.'))args.amount=Number(input('amount').value);if(action==='dev.time.set')args.hour=Number(input('hour').value);if(action==='dev.time.speed')args.speed=Number(input('speed').value);if(action==='dev.time.pause')args.paused=!clock.paused;command(args,action==='dev.interaction.resetCityVisit'?'Reset only the listed city-visit flags?':null);});$('#view').querySelectorAll('[data-encounter]').forEach(b=>b.onclick=()=>command({action:'dev.encounter.'+b.dataset.encounter,key:b.dataset.key},b.dataset.encounter==='reset'?`Revive only authored droids in ${b.dataset.key}?`:null));}
function common(kind,title){const list=work[kind];selection=Math.min(selection,Math.max(0,list.length-1));const chosen=list[selection];return `<div class="split"><div class="list"><label>Search ${esc(title)}<input id="search" value="${esc(search)}" placeholder="ID, name or tag"></label><div class="rows">${list.map((v,i)=>({v,i})).filter(({v})=>(v.id+' '+v.name+' '+(v.tags||[]).join(' ')).toLowerCase().includes(search.toLowerCase())).map(({v,i})=>`<button class="record ${selection===i?'selected':''}" data-index="${i}"><strong>${esc(v.name)}</strong><small>${esc(v.id)}</small>${badge}</button>`).join('')}</div><button id="newRecord">New ${esc(title.slice(0,-1))}</button></div><div class="editor">${chosen?`<h3>${esc(chosen.name)}</h3><p><code>${esc(chosen.id)}</code> · Stable ID (not renamable after creation).</p>`:'<p>Select or create a record.</p>'}<div id="editor"></div></div></div>`;}
function prepare(kind,title,newValue){wrap(title,common(kind,title)+actions());$('#search').oninput=e=>{search=e.target.value;render();$('#search').focus();};$('#view').querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{selection=Number(b.dataset.index);render();});$('#newRecord').onclick=()=>{const id=prompt('New stable ID (lowercase letters, digits, underscore):');if(!id)return;if(!/^[a-z][a-z0-9_]{1,63}$/.test(id)||Object.values(work).filter(Array.isArray).some(v=>v.some(x=>x.id===id))){notice('Invalid or duplicate stable ID');return;}work[kind].push(newValue(id));selection=work[kind].length-1;dirty=true;render();};}
function change(target,fn){fn();dirty=true;render();$('#view').querySelector(`[name="${target}"]`)?.focus();}
function draftEdited(message){dirty=true;$('#save').disabled=false;$('#discard').disabled=false;notice(message);}
function items(){prepare('items','Items',id=>({id,name:id,category:'Component',subtype:'',tier:1,rarity:'Common',weightKg:0,stack:20,tags:[],stats:{}}));const x=work.items[selection];if(!x)return;const runtime=live.state?.items?.find(i=>i.id===x.id),authored=unityCraft?.items?.find(i=>i.id===x.id);
$('#editor').innerHTML=(runtime?`<aside><h4>LIVE UNITY CATALOGUE · READ ONLY</h4><p>${esc(runtime.name)} · ${esc(runtime.description)}</p><p>Buy ${esc(runtime.buyPrice)} cr · Sell ${esc(runtime.sellPrice)} cr · Start ${esc(runtime.startingQuantity)} · Held ${esc(runtime.quantity)} · Cap ${esc(runtime.maxStack||'None')} · ${runtime.excludeFromTrade?'Not tradeable':'Tradeable'}</p><p>Authoritative tags: ${esc(runtime.tags?.join(', ')||'None')}</p></aside>`:authored?`<aside>Mapped by ID to Unity Editor export (not a live player). ${esc(authored.name)} · cap ${esc(authored.maxStack||'None')} · tags ${esc(authored.tags.join(', '))}.</aside>`:'<aside>Design-only ID: not mapped to Unity catalogue. Cannot be granted until separately authored in Unity.</aside>')+`<h4>Draft metadata only · edits do not change Unity</h4><div class="form">${field('Name',x.name,'name')}${field('Category',x.category,'category')}${field('Subtype',x.subtype,'subtype')}${field('Tier',x.tier,'tier','number','min="0" step="1"')}${field('Rarity',x.rarity,'rarity')}${field('Weight kg',x.weightKg,'weightKg','number','min="0" step="0.01"')}${field('Stack',x.stack,'stack','number','min="1" step="1"')}${field('Tags · comma-separated',x.tags.join(', '),'tags')}${field('Stats · JSON object',JSON.stringify(x.stats),'stats')}${field('Buy price · credits',x.buyPrice??0,'buyPrice','number','min="0" max="1000000" step="1"')}${field('Sell price · credits',x.sellPrice??0,'sellPrice','number','min="0" max="1000000" step="1"')}</div><label class="copy-field">Description<textarea name="description" maxlength="1200" rows="3">${esc(x.description||'')}</textarea></label><label class="copy-field">Design notes<textarea name="designNotes" maxlength="2000" rows="3">${esc(x.designNotes||'')}</textarea></label><button id="delete">Delete draft item</button>`;
$('#editor').querySelectorAll('input,textarea').forEach(i=>i.onchange=()=>{try{const k=i.name;x[k]=k==='tags'?i.value.split(',').map(v=>v.trim()).filter(Boolean):k==='stats'?JSON.parse(i.value):['tier','weightKg','stack','buyPrice','sellPrice'].includes(k)?Number(i.value):i.value;draftEdited('Unsaved draft edit.');window.refreshItemCopyReview?.();}catch(e){notice('Invalid stats JSON: '+e.message);}});$('#delete').onclick=()=>{if(confirm('Delete this draft item? Existing recipe/loot references will fail validation.')){work.items.splice(selection,1);dirty=true;render();}};window.mountItemAuthoring?.(x);}
function recipes(){prepare('recipes','Recipes',id=>({id,name:id,station:'station_field_fabricator',seconds:3,inputs:[{kind:'item',ref:work.items[0]?.id||'',quantity:1}],outputs:[{itemId:work.items[0]?.id||'',quantity:1}]}));const x=work.recipes[selection];if(!x)return;$('#editor').innerHTML=`<div class="form">${field('Name',x.name,'name')}${field('Station ID',x.station,'station')}${field('Craft time · seconds',x.seconds,'seconds','number','min="0" step="0.1"')}</div><h4>Inputs → station → output · draft design only</h4>${x.inputs.map((v,i)=>`<div class="row inputrow"><label>Kind<select data-input="${i}" data-key="kind"><option value="item" ${v.kind==='item'?'selected':''}>Exact item</option><option value="tag" ${v.kind==='tag'?'selected':''}>Tag predicate</option></select></label>${field('Item ID or tag',v.ref,'input-ref-'+i)}${field('Qty',v.quantity,'input-qty-'+i,'number','min="1" step="1"')}<button data-remove-input="${i}">Remove</button><small>${v.kind==='tag'?work.items.filter(t=>t.tags.includes(v.ref)).map(t=>t.name).join(', ')||'No tag matches':''}</small></div>`).join('')}<button id="addInput">Add item/tag input</button><h4>Outputs</h4>${x.outputs.map((v,i)=>`<div class="row">${field('Exact item ID',v.itemId,'output-id-'+i)}${field('Qty',v.quantity,'output-qty-'+i,'number','min="1" step="1"')}<button data-remove-output="${i}">Remove</button></div>`).join('')}<button id="addOutput">Add output</button><p>Valid item IDs: ${esc(work.items.map(v=>v.id).join(', '))}</p><button id="delete">Delete draft recipe</button>`;
$('#editor').querySelectorAll('input').forEach(i=>i.onchange=()=>{const k=i.name;if(k.startsWith('input-')){const [,field,index]=k.split('-');x.inputs[Number(index)][field==='qty'?'quantity':'ref']=field==='qty'?Number(i.value):i.value;}else if(k.startsWith('output-')){const [,field,index]=k.split('-');x.outputs[Number(index)][field==='qty'?'quantity':'itemId']=field==='qty'?Number(i.value):i.value;}else x[k]=k==='seconds'?Number(i.value):i.value;draftEdited('Unsaved recipe draft.');});$('#editor').querySelectorAll('[data-input]').forEach(el=>el.onchange=()=>{x.inputs[Number(el.dataset.input)].kind=el.value;dirty=true;render();});$('#editor').querySelectorAll('[data-remove-input]').forEach(el=>el.onclick=()=>{x.inputs.splice(Number(el.dataset.removeInput),1);dirty=true;render();});$('#editor').querySelectorAll('[data-remove-output]').forEach(el=>el.onclick=()=>{x.outputs.splice(Number(el.dataset.removeOutput),1);dirty=true;render();});$('#addInput').onclick=()=>{x.inputs.push({kind:'item',ref:work.items[0]?.id||'',quantity:1});dirty=true;render();};$('#addOutput').onclick=()=>{x.outputs.push({itemId:work.items[0]?.id||'',quantity:1});dirty=true;render();};$('#delete').onclick=()=>{if(confirm('Delete this recipe draft?')){work.recipes.splice(selection,1);dirty=true;render();}};}
function enemies(){prepare('enemies','Enemies',id=>({id,name:id,loot:[]}));const x=work.enemies[selection];if(!x)return;$('#editor').innerHTML=`<aside>Draft loot only. Unity droids have separate authored loot tables; edits here do not change them.</aside>${field('Name',x.name,'name')}<h4>Loot entries · chance % and quantity bounds</h4>${x.loot.map((v,i)=>`<div class="row lootrow">${field('Item ID',v.itemId,'loot-id-'+i)}${field('Min',v.min,'loot-min-'+i,'number','min="0" step="1"')}${field('Max',v.max,'loot-max-'+i,'number','min="0" step="1"')}${field('Chance %',v.chance,'loot-chance-'+i,'number','min="0" max="100" step="0.1"')}<button data-remove="${i}">Remove</button></div>`).join('')}<button id="addDrop">Add loot entry</button><p>Design estimate only; the separate Unity loot table is authoritative.</p><button id="delete">Delete draft enemy</button>`;$('#editor').querySelectorAll('input').forEach(i=>i.onchange=()=>{const k=i.name;if(k.startsWith('loot-')){const [,key,index]=k.split('-');x.loot[Number(index)][key==='id'?'itemId':key]=key==='id'?i.value:Number(i.value);}else x.name=i.value;draftEdited('Unsaved loot draft.');});$('#editor').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{x.loot.splice(Number(b.dataset.remove),1);dirty=true;render();});$('#addDrop').onclick=()=>{x.loot.push({itemId:work.items[0]?.id||'',min:1,max:1,chance:100});dirty=true;render();};$('#delete').onclick=()=>{if(confirm('Delete this draft enemy?')){work.enemies.splice(selection,1);dirty=true;render();}};}
function graph(){const edges=[],used=new Set(),produced=new Set(),seeded=new Set(),ids=new Set(work.items.map(i=>i.id)),tags=new Map(work.items.map(i=>[i.id,i.tags]));for(const e of work.enemies)for(const d of e.loot)if(d.chance>0&&d.max>0)seeded.add(d.itemId);for(const r of work.recipes)for(const inp of r.inputs)for(const out of r.outputs){let sources=inp.kind==='item'?[inp.ref]:work.items.filter(i=>i.tags.includes(inp.ref)).map(i=>i.id);sources.forEach(s=>{edges.push({from:s,to:out.itemId,via:r.id});used.add(s);});produced.add(out.itemId);}let available=new Set(seeded);for(let n=0;n<=ids.size;n++){let old=available.size;for(const r of work.recipes)if(r.inputs.every(v=>v.kind==='item'?available.has(v.ref):[...available].some(id=>tags.get(id)?.includes(v.ref))))r.outputs.forEach(o=>available.add(o.itemId));if(available.size===old)break;}const adj=new Map([...ids].map(id=>[id,[]]));for(const e of edges)adj.get(e.from)?.push(e.to);const active=new Set(),seen=new Set(),circular=new Set();function walk(id){if(active.has(id)){circular.add(id);return;}if(seen.has(id))return;seen.add(id);active.add(id);for(const to of adj.get(id)||[])walk(to);active.delete(id);}for(const id of ids)walk(id);const list=(label,values)=>`<p><strong>${label}</strong>: ${values.length?values.map(esc).join(', '):'None detected'}</p>`;const itemButton=id=>`<button class="node" data-node="${esc(id)}">${esc(id)}</button>`;wrap('Dependency graph',`${actions()}<article><h3>Draft relationships · navigable graph</h3><p>Edges are design-only. Select any item node to open its inspector. This edge list is a keyboard-accessible graph.</p>${list('Orphan items', [...ids].filter(i=>!used.has(i)&&!produced.has(i)&&!seeded.has(i)))}${list('Impossible outputs (based on draft loot seeds)', [...produced].filter(i=>!available.has(i)))}${list('Circular dependencies', [...circular])}<ol>${edges.map(e=>`<li>${itemButton(e.from)} → ${itemButton(e.to)} via ${esc(e.via)} · ${badge}</li>`).join('')}</ol><h4>Enemy → drops · draft</h4><ol>${work.enemies.flatMap(e=>e.loot.map(d=>`<li>${esc(e.name)} → ${itemButton(d.itemId)} · ${esc(d.chance)}% · ${badge}</li>`)).join('')}</ol></article>`);$('#view').querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{selection=work.items.findIndex(i=>i.id===b.dataset.node);if(selection<0){notice('Unknown draft node');return;}tab='items';search='';render();});}
function authoredMapping(){
 if(!['recipes','enemies'].includes(tab))return;
 const row=work[tab][selection],panel=$('#editor');if(!row||!panel)return;
 const record=unityCraft?.[tab]?.find(x=>x.id===row.id);
 let detail='';
 if(tab==='recipes'&&record)detail=`Station ${record.stationId}; requires ${record.requiresWeaponId}; inputs ${record.inputs.map(x=>`${x.kind}:${x.id} ×${x.quantity}`).join(', ')}; output ${record.outputItemId} ×${record.outputQuantity}.`;
 if(tab==='enemies'&&record){const table=unityCraft.lootTables?.find(x=>x.id===record.lootTableId);detail=`Prefab ${record.prefab}; loot ${table?.entries?.map(x=>`${x.itemId} ×${x.quantity} @ ${Math.round(x.chance*100)}%`).join(', ')||'not found'}.`;}
 const aside=document.createElement('aside');aside.textContent=record?`Unity Editor export snapshot · ID match only, not draft parity. ${detail}`:'Design-only ID · no matching Unity Editor export record. Draft edits never write Unity assets.';
 panel.prepend(aside);
}
function render(){if(!work)return;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));({session,items,recipes,enemies,graph,creative:window.creativeDesk})[tab]();authoredMapping();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(dirty&&tab!=='session')notice('Unsaved draft edits remain in memory; Save before leaving.');tab=b.dataset.tab;selection=0;search='';render();});
(async()=>{try{token=(await api('config')).token;await refreshDraft();await refreshUnityCraft();await refreshLive();await window.authoringInit?.();setInterval(refreshLive,1000);}catch(e){notice('Failed to start: '+e.message);}})();
